Fase_2/Fase_2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from Menu import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Menu/',include('Menu.urls')),
    path('Contacto/',views.contacto,name='Contacto'),
    path('Sobre_Nosotros/',views.sobre_nosotros,name='Sobre_Nosotros'),
    
]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Fase_2/Menu/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name='index'),
]

Fase_2/Menu/models.py
from django.db import models
from django.urls import reverse
import uuid 

# Create your models here.

class Menu(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    promociones=models.CharField(max_length=100, null=True)
    acompañamientos=models.CharField(max_length=100, null=True)
    bebidas=models.CharField(max_length=50, null=True)
    precio=models.IntegerField(default=1, blank=True, null=True )

    def get_absolute_url(self):
        return reverse('pizza-detail', args=[str(self.id)])

    def __str__(self):
        return self.promociones

class Contacto(models.Model):
    email=models.EmailField()
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    fono=models.IntegerField()
    direccion=models.CharField(max_length=100)
    fecha=models.DateField(auto_now=True)

    motivo_cotacto=[
        ('VentadePizzas', 'Freshman'),
        ('EventosCorporativos', 'Sophomore'),
        ('Alianzas', 'Junior'),
        ('ProblemasConTuPedido', 'Senior'),
        ('Comentarios', 'Graduate'),
    ]

    motivo=models.CharField(max_length=100, choices=motivo_cotacto)

    def __str__(self):
        return self.nombre, self.apellido

Fase_2/Menu/forms.py
from django import forms
from .models import Contacto

class Peticiones(forms.Form):
    nombre = forms.CharField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))
    Direccion = forms.CharField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))

    Apellido =forms.CharField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))

    fono = forms.IntegerField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))
    email = forms.EmailField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))
    fecha = forms.DateField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))
    
    motivo = forms.CharField(required=True, max_length=100, widget=forms.TextInput(
        attrs = {
            'class':'form-control p-4'
        }
    ))
    

Fase_2/Menu/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import Menu,Contacto
from django.views import generic
from django.http import HttpResponse


# Create your views here.

def index(request):
    num = Menu.objects.all()

    return render(
        request,
        'index.html',
        context={'num':num}
    )

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
class PizzaDetalles(generic.DetailView):
    model = Menu


def contacto(request):
    if request.method=="POST":
        contacto=Contacto()
        nombre=request.POST.get('nombre')
        email=request.POST.get('email')
        apellido=request.POST.get('apellido')
        fono=request.POST.get('fono')
        direccion=request.POST.get('direccion')
        fecha=request.POST.get('fecha')
        motivo=request.POST.get('motivo')

        contacto.nombre=nombre
        contacto.email=email
        contacto.apellido=apellido
        contacto.fono=fono
        contacto.direccion=direccion
        contacto.motivo=motivo
        contacto.save()
        return HttpResponse("<h1>GRACIAS POR CONTACTARNOS</h1>")
    return render(request,'Contacto.html')

def sobre_nosotros(request):
    return render(request,'Sobre_Nosotros.html')

Fase_2/Menu/templates/Contacto.html
{% extends "base_generic.html" %}

{%load static%}
<br>
<body background="../static/img/Fondo1.jpg">
    {%block content%}


               
        <style>
            body {
               
                font-family: Arial;
                
              }
        
            input {
                float: left ;
                width: 200px;
                margin-bottom: 10px;
            }
        
            label {
                color: white;
                clear: both;
                float: left ;
                width: 180px;
            }
        
            button {
                clear: both;
                float: left;
                width: 60px;
            }
        
            .error-control {
                border: 1px solid red;
            }
        
            label.error {
                color: red;
                width: 300px;
                font-size: 0.8em;
                margin-top: -5px;
                margin-bottom: 10px;
            }
            
        
        
          </style>
         
          <script>
    
              $(function() 
              {
                $("#mi-formulario").validate({
                     rules: {
                            email: {
                                required: true,
                                email: true
                            },
                            fono: "required",
                            fecha: "required",
                        }, //rules
                    messages: {
                        email: {
                            required: 'Ingresa tu correo electrónico',
                            email: 'Formato de correo no válido'
                        },
                        Nombre: {
                            required: 'Ingresa un Nombre',
                            minlength: 'Caracteres insuficiente'
                        },
                        Apellido: {
                            required: 'Ingresa un Apellido',
                            minlength: 'Caracteres insuficiente'
                        },
                        Direccion: {
                            required: 'Ingresa una Direccion',
                            minlength: 'Caracteres insuficiente'
                        },
                        fono:{
                            required: 'Ingrese un número de celular',
                            minlength: 'Cantidad de digitos insuficiente'
                        },
                        fecha:{
                            required: 'Seleccione una fecha válida',
                            min: 'Fecha no corresponde'
                        },
                        
                        
                    }//messages
                }); //$('#mi-formulario').validate
            }); //function
        
          </script>
           
        </head>
       
        <body>
         
            <div class="espacio" style="height:80px" ></div>
            <div class="test3" style="margin-left: auto;">
                <h3 style="margin-left:auto">Formulario de contacto Pizzas Covid</h3>
                <br>
            <form id="mi-formulario" method="POST">
                {% csrf_token %}
                <label>Correo Electrónico: </label>
                <input type="text" name="email" required placeholder="nombre@dominio.cl" minlength="11">
              
                <label>Nombre: </label>
                <input id="nom" type="text" name="nombre" required  >
              
                <label>Apellido: </label>
                <input type="text" name="apellido" required>
        
                <label>Telefono:</label>
                <input type="text" name="fono" minlength="9">
                  
                <label>Direccion:</label>
                <input type="text" name="direccion" required>
    
                <label>Fecha:</label>
                <input type="date" name="fecha" min="2018-01-01" required="">
                <br> <br><br><br><br><br><br><br><br><br>
                <label>Motivo:</label>
                <select name="motivo" id="id_motivo">
                    <option value="" selected="selected">Selecione una opcion</option>
                    <option value="v">Venta de pizzas</option>
                    <option value="c">Eventos corporativos</option>
                    <option value="a">Alianzas</option>
                    <option value="p">Problemas con tu pedido</option>
                    <option value="q">Comentarios</option>
                </select>
                <br> 
                <textarea name="comentarios" rows="10" cols="40"></textarea>
    
                   
    
                <button> Enviar </button>
              </form>
            </div>
           
        </body>

    <!----------->

</body>
{% endblock %}

Fase_2/Menu/templates/Sobre_nosotros.html
{% extends "base_generic.html" %}
{%load static%}

<br>
<body background="../static/img/Fondo1.jpg">
    {%block content%}
        <div>
            <div class="espacio" style="height:100px"></div>

            <div class=test1>
                <article class="col1">	
                    <div class="row">       
                        <div class="col-md">        
                            <div class="card" style="background:  silver">      
                              <div class="card-body">
                                <p class="font1">
                                    Somos una pizzeria con gran experiencia en la elaboración de todos y cada uno de nuestros productos, 
                                    priorizamos los alimentos de gran calidad y de origen local que nos permiten crear pizzas de manera artesana 
                                    en horno de piedra, buscamos un sabor autentico en cada una de nuestras pizzas.
                                </p>
                              </div>
                            </div>          
                        </div>
                </article>
            </div>
        <div>
            <img src="../static/img/logo.png" style="width: 300px;" > 
        </div>
        
     
        <div class="espacio" style="height:50px"></div>

            <div class="test2">
            <article class="col2">
                <h5 class="subtitulo">Clientes</h5>
                    <div class="row">       
                        <div class="col-md">        
                            <div class="card" style="background:  silver">      
                              <div class="card-body">
                                <p class="card-c">
                                    Toda opinión es muy importante para la elaboración de nuestras pizzas, por ello escuchamos y tendremos en cuenta cada detalle y sugerencia que nos puedas ofrecer. 
                                    
                                </p>
                              </div>
                            </div>          
                        </div>
            </article>
            <article class="col3"> 
                <h5 class="subtitulo" >Ingredientes</h5>  
                    <div class="row">       
                        <div class="col-md">        
                            <div class="card" style="background:  silver">      
                              <div class="card-body">
                                <p class="card-contact">
                                    Siempre trabajamos con productos frescos, de calidad y de origen local que nos garantizan ingredientes deliciosos y consistentes en nuestras pizzas. </p>
                              </div>
                            </div>          
                        </div>
            </article>
            <article class="col4">
                <h5 class="subtitulo">Pizzas</h5>
                    
                    <div class="row">       
                        <div class="col-md">        
                            <div class="card" style="background: silver">      
                              <div class="card-body">
                                <p class="card-contact">
                                    Buscamos combinaciones diferentes que proporcionen una experiencia nueva en la que el sabor tradicional y artesanal también tengan una alta presencia. 
                                </p>
                              </div>
                            </div>          
                        </div>
            </article>
            <article class="col5">
                <h5 class="subtitulo">Experiencia</h5>
                    <div class="row">       
                        <div class="col-md">        
                            <div class="card" style="background: silver">      
                              <div class="card-body">
                                <p class="card-contact">
                                    Con todos los puntos anteriores presentes encontramos la clave para proporcionar un equilibrio en nuestras pizzas que garanticen su sabor. 
                                </p>
                              </div>
                            </div>          
                        </div>
            </article>  
            </div>
        </div>


        
</body>
{% endblock %}

Fase_2/Menu/templates/base_generic.html
<!DOCTYPE html>

<html lang="es-Cl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PizzaDominoHutTeleJhons</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

<br>
<body background="img/Fondo1.jpg">
    <header>
      <h1  ><img src="{% static 'img/logo.png'%}" style="width: 70px;" > Pizzas Covid "Para morir de sabor"<img src="{% static 'img/logo.png'%}" style="width: 70px;" ></h1>
      <br>
        <nav class="navBar navbar-expand-lg navbar-light bg-light">
            <button id="uwu" 
                class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
         
            <div class="collapse navbar-collapse justify-content-between alingn-items-center w-100" style="background:silver "  >

                <ul class="navbar-nav mx-auto nav-tabs text-lg-center text-left" style="background:silver  " >
                    <li class="nav-link" ><a href="{% url 'index'%}" style="color: black;">Inicio </a></li>
                    <li class="nav-link"><a href="{% url 'Sobre_Nosotros'%}" style="color: black;">Sobre Nosotros</a></li>
                    <li class="nav-link"><a href="{% url 'Contacto'%}"  style="color: black;">Contacto</a></li>
                </ul>
            </div>
        </nav>
    </header>

    {% block content %} {% endblock %}

      <div class="espacio" style="height:60px"></div>

      <div class="prueba3">
          <footer id="footer">
              <div id="inner">
                  <div class="col7">
                      <div class="minititulo">
                          Contacto
                          <div class="espacio" style="height:30px"></div>
                      </div>
                      <div class="miniparrafo">
                          <img src="{% static 'img/house.png'%}" style="width: 20px;" > Esquina Blanca 501  Maipú Región Metropolitana
                      </div>
                      <div class="miniparrafo">
                          <div class="espacio" style="height:10px"></div>
                          <img src="{% static 'img/phone-call.png'%}" style="width: 20px;" > +56987654321
                      </div>
                      <div class="miniparrafo">
                          <div class="espacio" style="height:10px"></div>
                          <img src="{% static 'img/envelope.png'%}" style="width: 20px;" > info@pizzascovids.com.hk
                      </div>
                      <div class="miniparrafo">
                          <div class="espacio" style="height:10px"></div>
                          <img src="{% static 'img/link.png'%}" style="width: 20px;" > http://www.pizzascovid.com.hk
                      </div>
                  
                  </div>
                  <div class="col8">
                      <div class="minititulo">
                          Horarios
                          <div class="espacio" style="height:30px"></div>
                      </div>
                      <div class="miniparrafo">
                          Lunes 12:00 - 22:00 
                      </div>
                      <div class="miniparrafo">
                         Martes 12:00 - 22:00 
                      </div>
                      <div class="miniparrafo">
                          Miercoles 12:00 - 22:00 
                      </div>
                      <div class="miniparrafo">
                          Jueves 12:00 - 22:00 
                      </div>
                      <div class="miniparrafo">
                          Viernes 12:00 - 02:00 
                      </div>
                      <div class="miniparrafo">
                         Sabados 12:00 - 02:00 
                      </div>
                      <div class="miniparrafo">
                          Domingos Cerrado
                      </div>
                  </div>
                  <div class="col9">
                      <div class="minititulo">
                          Mapa
                      </div>
                      <img src="{% static 'img/mapa.jpg'%}" style="width: 325px;" > </a> 
                      <div class="espacio" style="height:30px"></div>
                  </div>
              </div>
          </footer> 
      </div>

      <div class="espacio" style="height:50px"></div>
   

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>


</body>
</html>

Fase_2/Menu/templates/index.html
{% extends "base_generic.html" %}
<!DOCTYPE html>

<html lang="es-Cl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PizzaDominoHutTeleJhons</title>´
    {% load static %}
    <link rel="stylesheet" href="static'css/estilos.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<br>
<body background="../static/img/Fondo1.jpg">
    {% block content %}
    <main>
        <section id="main">
          <div class=prueba1>
              <article class="col">
                <h2 >Promociones covid individual</h2>
                <div class="row">       
                  <div class="col-md">        
                      <div class="card" style="background: black">
                        <img class="card-img-top" src="../static/img/promo1.jpg" alt="150" height="550" width="100" aling ="center">            
                        <div class="card-body" >
                          <p class="card-text">Promocion Pizza pequeña (3 ingredientes a eleccion) con acompañamiento simple(a eleccion) y una bebida de 3LT </p>
                          <a href="https://www.pizzapizza.cl/promociones/" class="btn btn-primary" >Pedir</a>
                        </div>
                      </div>          
              </div>
            </article>
          </div>
            <br>
            <br>
            <div class=prueba1>
            <article class="col">
                <h2 >Promociones covid mediano</h2>
                
                <div class="row">       
                  <div class="col-md">        
                      <div class="card" style="background: black">
                        <img class="card-img-top" src="../static/img/promo2.jpg" alt="150" height="550" width="100" aling ="center">            
                        <div class="card-body">
                          <p class="card-text">Promocion Pizza mediana (3 ingredientes a eleccion) y una bebida de 2LT</p>
                          <a href="https://www.pizzapizza.cl/promociones/" class="btn btn-primary">Pedir</a>
                        </div>
                      </div>          
                  </div>
            </article>
          </div>
            <br>
            <br>
            <div class=prueba1>
            <article class="col">
                <h2 >Promociones covid familiar </h2>
                <div class="row">       
                  <div class="col-md">        
                      <div class="card" style="background: black">
                        <img class="card-img-top" src="../static/img/promo3.jpg" alt="150" height="550" width="100" aling ="center">            
                        <div class="card-body">
                          <p class="card-text" >Promocion Pizza familiar (3 ingredientes a eleccion) con 3 acompañamientos a eleccion y una bebida de 1.5LT</p>
                          <a href="https://www.pizzapizza.cl/promociones/" class="btn btn-primary">Pedir</a>
                        </div>
                        
                      </div>          
                  </div>
            </article>
          </div>
        </section>
        <div class=carrusel>
        <!--------------Carrusel----------------------------->
        <br>
        <br>
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="../static/img/Pizza1.jpg"  class="d-block w-100" alt="350" height="350" width="100" aling =" center"  >
              <div class="carousel-caption d-none d-md-block">
                <h5 style="color: black;" >Combo Supremo</h5>
                <p style="color: black;" >Este combo incluye: Pizza todas las carnes,bebida de 1.5,nugges de pollo y papas supremas pequeña</p>
              </div>
            </div>
         
            <div class="carousel-item">
              <img src="../static/img/pizza2.jpg" class="d-block w-100" alt="350" height="350" width="200" aling =" center" >
              <div class="carousel-caption d-none d-md-block">
                <h5 style="color: black;">Combo amigos</h5>
                <p style="color: black;">Esta Promo contiene 2 Pizzas mediana, con 3 acompañamientos (a eleccion) y una bebida de 1.5LT</p>
            </div>
            
            </div>
            <div class="carousel-item">
              <img src="../static/img/pizza3.jpg" class="d-block w-100" alt="350" height="350 " width="200" aling =" center" >
              <div class="carousel-caption d-none d-md-block">
                <h5 style="color: black;">Combo peperoni</h5>
                <p style="color: black;">Esta promocion contiene pizza de peperoni,bebida de 1.5lts y acompañamiento a eleccion</p>
              
              </div>
            </div>
            
          </div>
          
          <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
          <!--------------Carrusel----------------------------->
        </div>
    </main>


      {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>


</body>